{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "## Exercises\n",
    "\n",
    "### Exercise 1\n",
    "\n",
    "Print \"condition is true\" if x is greater than or equal to y.\n",
    "\n",
    "x = 3\n",
    "y = 1\n",
    "\n",
    "# Don't be afraid to be wrong!\n",
    "if x >= y:\n",
    "  print(\"condition is true\")\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# _____(x ___ y):\n",
    "#     print(\"True\")\n",
    "\n",
    "### Exercise 2\n",
    "\n",
    "Print \"x is not equal to y\" if x is not equal to y,  \n",
    "print \"x is equal to y\" if x is equal to y.\n",
    "\n",
    "x=5\n",
    "y=5\n",
    "\n",
    "# Coding is a journey!\n",
    "if x == y:\n",
    "   print(\"x is equal to y\")\n",
    "else:   \n",
    "   print(\"x is not equal to y\")   \n",
    "\n",
    "  \n",
    "\n",
    "##### Hint\n",
    "\n",
    "# if(x __ y):\n",
    "#     print(\"x is not equal to y\")\n",
    "# else:\n",
    "#     print(\"x is equal to y\")\n",
    "\n",
    "### Exercise 3\n",
    "\n",
    "\n",
    "\n",
    "Write an `if` statement that asks for the user's name using the `input()` function.  \n",
    "If the name is \"Bond\", make it print \"Welcome on board 007.\"  \n",
    "Otherwise, make it print \"Good morning NAME\". (Replace NAME with the user's name).\n",
    "\n",
    "# Code with confidence!\n",
    "x = input(\"Please enter your username. \")\n",
    "if x == \"Bond\":\n",
    "  print(\"Welcome on board 007.\")\n",
    "else:\n",
    " print(f\"Good morning {x}\")  \n",
    "\n",
    "##### Hint\n",
    "\n",
    "# name = _____()\n",
    "# if name _____ \"Bond\":\n",
    "#     print(\"Welcome on board 007\")\n",
    "# else:\n",
    "#     print(f\"Good morning _____\")\n",
    "\n",
    "### Exercise 4\n",
    "\n",
    "Print the results of the following:\n",
    " - If x is greater than y, subtract x from y.\n",
    " - If x is smaller than y, add x to y.\n",
    " - If x is equal to y, multiply x by y.\n",
    "\n",
    "x=3\n",
    "y=3\n",
    "\n",
    "# You've got this!\n",
    "if x > y:\n",
    "  print(y - x)\n",
    "elif x < y:\n",
    "  print(x + y)\n",
    "else x == y:\n",
    "  print(x * y)  \n",
    "\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# _____ x > y:\n",
    "#     print(y - x)\n",
    "# elif x _____ y:\n",
    "#     print(y + x)\n",
    "# _____\n",
    "#     print(y * x)\n",
    "\n",
    "### Exercise 5\n",
    "\n",
    "Use if statements to find which value is the biggest one and print \"The biggest value is VALUE.\".\n",
    "BONUS: Check out the solution with nested statements.\n",
    "\n",
    "x=83\n",
    "y=45\n",
    "z=45\n",
    "\n",
    "# Don't be afraid to experiment!\n",
    "if z >= y and z >= x:\n",
    "  print(f\"The biggest value is {z}\")\n",
    "elif y >= z and y >= x:\n",
    "  print(f\"The biggest value is {y}\")\n",
    "elif x >= y and x >= z:\n",
    "  print(f\" The biggest value is {x}\")    \n",
    "\n",
    "##### Hint\n",
    "\n",
    "# if _____ >= y _____ x >= z:\n",
    "#     print(f\"The biggest value is {x}\")\n",
    "# _____ y >= x and _____ >= z:\n",
    "#     print(f\"The biggest value is {_____}\")\n",
    "# else:\n",
    "#     print(f\"The biggest value is {z}\")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
