{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "# 7.&nbsp; Exercises\n",
    "\n",
    "#### Exercise 1\n",
    "\n",
    "Create a list named `lower_names` and fill it with your favourite actors. Include name and surname, all in lowercase (like `john doe`).\n",
    "Then, create a new list `capital_names` with both the names and surnames capitalized (like `John Doe`), by iterating through the first list with a `for` loop.\n",
    "\n",
    "# It's okay to make mistakes!\n",
    "lower_names = [\"jacob elordi\", \"sydney sweeney\", \"austin butler\", \"sadie sink\", \"noah schnapp\"]\n",
    "capital_names = []\n",
    "\n",
    "for name in lower_names:\n",
    "  capital_names.append(name.title())\n",
    "print(capital_names)\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# lower_names = [\"_____ _____\",\"_____ _____\",\"_____ _____\",\"_____ _____\",\"_____ _____\",\"_____ _____\"]\n",
    "# capital_names = []\n",
    "# _____ name in _____:\n",
    "#     capital_names._____(name._____())\n",
    "\n",
    "#### Exercise 2\n",
    "\n",
    "Use the `capital_names` list from the previous exercise and print out only the ones that start with \"A\" or \"J\".\n",
    "\n",
    "for name in capital_names:\n",
    "  if name.startswith(\"A\") or name.startswith(\"J\"):\n",
    "    print(name)\n",
    "\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# for name in _____:\n",
    "#     if _____.startswith(\"A\") or name._____(\"J\"):\n",
    "#         print(_____)\n",
    "\n",
    "#### Exercise 3\n",
    "\n",
    "You are given a list of names. Loop through the list and print \"Hello `name`!\" if a name starts with \"A\". If not, print \"Bye `name`!\".\n",
    "\n",
    "names = [\"Justine\",\"Amabel\",\"Karl\",\"Anna\",\"Lina\",\"Sergei\",\"Wang\",\"Aurora\"]\n",
    "\n",
    "# Coding is your superpower; use it to conquer the challenge\n",
    "for name in names:\n",
    "  if name.startswith(\"A\"):\n",
    "    print(f\"Hello {name}\")\n",
    "  else:\n",
    "    print(f\"Bye {name}\")\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# for _____ in names:\n",
    "#     if name._____(\"A\"):\n",
    "#         print(\"Hello \"+_____+\"!\")\n",
    "#     _____:\n",
    "#         print(\"Bye \"+_____+\"!\")\n",
    "\n",
    "#### Exercise 4\n",
    "\n",
    "Copy the code from last exercise and add a text that gets printed after each iteration of the loop, so it is clearer what\"s going on. (\"Next iteration incoming...\")\n",
    "\n",
    "# Write code with confidence\n",
    "for name in names:\n",
    "  if name.startswith(\"A\"):\n",
    "    print(f\"Hello {name}\")\n",
    "    print(\"Next iteration incoming...\")\n",
    "  else:\n",
    "    print(f\"Bye {name}\")\n",
    "    print(\"Next iteration incoming...\")\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# for _____ in names:\n",
    "#     if name._____(\"A\"):\n",
    "#         print(\"Hello \"+_____+\"!\")\n",
    "#     _____:\n",
    "#         print(\"Bye \"+_____+\"!\")\n",
    "#     _____(\"Next iteration incoming...\")\n",
    "\n",
    "#### Exercise 5\n",
    "\n",
    "In the previous code, the \"next iteration incoming...\" text gets printed also for the last iteration, which might be confusing for whoever reads the output of this code. Change the code so that this text gets printed in all except the last iteration.\n",
    "\n",
    "names = [\"Justine\",\"Amabel\",\"Karl\",\"Anna\",\"Lina\",\"Sergei\",\"Wang\",\"Aurora\"]\n",
    "\n",
    "for name in names:\n",
    "  if name == names[-1] and name.startswith(\"A\"):\n",
    "        print(f\"Hello {name}\")\n",
    "        break\n",
    "  if name == names[-1] and name.startswith(\"J\"):\n",
    "        print(f\"Bye {name}\")\n",
    "        break\n",
    "  if name.startswith(\"A\"):\n",
    "    print(f\"Hello {name}\")\n",
    "    print(\"Next iteration incoming...\")\n",
    "  else:\n",
    "    print(f\"Bye {name}\")\n",
    "    print(\"Next iteration incoming...\")\n",
    "\n",
    "# Stay curious and keep coding\n",
    "for name in names:\n",
    "  if name == \"Aurora\":\n",
    "    print(f\"Hello {name}\")\n",
    "    break\n",
    "  if name.startswith(\"A\"):\n",
    "    print(f\"Hello {name}\")\n",
    "    print(\"Next iteration incoming...\")\n",
    "  else:\n",
    "    print(f\"Bye {name}\")\n",
    "    print(\"Next iteration incoming...\")\n",
    "\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# count = _____\n",
    "# for _____ in names:\n",
    "#     if name._____(\"A\"):\n",
    "#         print(\"Hello \"+_____+\"!\")\n",
    "#     if _____ != len(names):\n",
    "#         print(\"Next iteration incoming...\")\n",
    "#     _____ = _____ 1\n",
    "\n",
    "#### Exercise 6\n",
    "\n",
    "You are given a list of numbers. Looping through the list, sum all the numbers and print the result.\n",
    "\n",
    "numbers = [23,45,12,10,25]\n",
    "\n",
    "# Embrace the challenge\n",
    "sum = 0\n",
    "for number in numbers:\n",
    "  sum += number\n",
    "  print(sum)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# total = 0\n",
    "# for number in _____:\n",
    "#     _____ = _____ number\n",
    "# print(_____)\n",
    "\n",
    "#### Exercise 7\n",
    "\n",
    "Create a simple calculator for additions!\n",
    "Repeatedly ask the user to enter numbers. Each time that the user provides input, this input is first converted to float and then added to a variable `total` (which should start from 0).\n",
    "When the user enters \"add\", the loop stops and the running total is printed out.\n",
    "\n",
    "# Bugs are just detours on the road to success; keep coding!\n",
    "count = 0\n",
    "while True:\n",
    "  entered_number = (input(\"Please enter a random number \"))\n",
    "  if entered_number == \"add\":\n",
    "    print(\"User entered add, stopping loop\")\n",
    "    break\n",
    "  entered_number = float(entered_number)\n",
    "  if entered_number >= 0:\n",
    "     count += entered_number\n",
    "     print(count)\n",
    "  else:\n",
    "    print(\"Entered number is negative, stopping loop\")\n",
    "    break\n",
    "    \n",
    "\n",
    "\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# total = 0\n",
    "# while True:\n",
    "#     print(\"Enter number or write 'add' to sum all previous inputs.\")\n",
    "#     _____ = input()\n",
    "#     if number == _____:\n",
    "#         break\n",
    "#     else:\n",
    "#         _____ += float(_____)\n",
    "# print(_____)\n",
    "\n",
    "# 8.&nbsp; Bonus exercises\n",
    "\n",
    "\n",
    "\n",
    "# some lists to work with\n",
    "\n",
    "car_brands = [\"BMW\", \"Volkswagen\", \"Mercedes\", \"Ford\", \"Apple\", \"Toyota\",\n",
    "              \"Tesla\", \"Kia\", \"Porsche\", \"Mazda\", \"Honda\", \"Jaguar\",\n",
    "              \"Mitsubishi\", \"Audi\", \"Bentley\", \"Bugatti\", \"Chrysler\"]\n",
    "\n",
    "fibonacci = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 53, 89, 144]\n",
    "\n",
    "characters = [[\"Harry\", \"Hermione\", \"Ron\"],\n",
    "              [\"Daenerys Targaryen\", \"Jon Snow\", \"Tyrion Lannister\",\n",
    "               \"Cercei Lannister\", \"Arya Stark\", \"Sansa Stark\"],\n",
    "              [\"Aragorn\", \"Gandalf\", \"Frodo\", \"Legolas\", \"Gollum\", \"Gimli\"],\n",
    "              [\"Walter White\", \"Jesse Pinkman\", \"Gus Fring\"]\n",
    "             ]\n",
    "\n",
    "sex_and_the_city = [\"Carrie\", \"Samantha\", \"Charlotte\", \"Miranda\"]\n",
    "\n",
    "numbers = [1, 51, 59, 2, 95, 25, 28, 67, 14, 63, 84, 33, 56, 31, 54, 97, 77,\n",
    "            98, 46, 84, 6, 66, 86, 77, 69, 19, 77, 7, 76, 19, 59, 77, 28, 34,\n",
    "            94, 4, 45, 95, 41, 66, 5, 38, 35, 57, 84, 38, 94, 65, 45, 80, 83,\n",
    "            22, 12, 100, 52, 55, 31, 69, 29, 67, 4, 39, 87, 49, 81, 82, 96, 4,\n",
    "            85, 62, 90, 72, 70, 26, 29, 63, 48, 94, 58, 9, 49, 79, 33, 63, 41,\n",
    "            13, 90, 37, 31, 3, 11, 54, 56, 72, 91, 97, 2, 83, 82, 6]\n",
    "\n",
    "#### Exercise 8\n",
    "\n",
    "Implement the for loop that greets people for the `characters` list you used in the previous exercises. For now, do not include any condition —just say hello to every character. What do you need to do to iterate through lists inside a list?\n",
    "\n",
    "# You're on the right track; keep coding and stay determined.\n",
    "harry_potter = characters[0]\n",
    "game_thrones = characters[1]\n",
    "lord_rings = characters[2]\n",
    "breaking_bad = characters [3]\n",
    "\n",
    "print(harry_potter)\n",
    "print(game_thrones)\n",
    "print(lord_rings)\n",
    "print(breaking_bad)\n",
    "\n",
    "for c in characters:\n",
    "  print(c)\n",
    "  for p in c:\n",
    "    print(f\"Hello {p}\")\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# for _____ in characters:\n",
    "#     for character in _____:\n",
    "#         print(\"Hello \" + character)\n",
    "\n",
    "#### Exercise 9\n",
    "\n",
    "Tweak the code of the previous exercise to greet characters based on these conditions:\n",
    "\n",
    "- If their name is composed of two words (Name Surname), the greeting should be \"Hello Name, from the house of Surname\".\n",
    "\n",
    "- If their first (or only) name is shorter than 6 characters, the greeting should replicate the last letter of the name as many times as needed until it reaches 6 characters.\n",
    "\n",
    "# Solve it with code!\n",
    "for c in characters:\n",
    "  print(c)\n",
    "  for p in c:\n",
    "    print(f\"Hello {p}\")\n",
    "    if len(p.split()) == 2:\n",
    "      print(f\"Hello {first_name}, from the hous of {second_name}\")\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# for _____ in characters:\n",
    "#     for character in _____:\n",
    "#         list_of_names = _____.split(\" \")\n",
    "#         first_name = _________\n",
    "#         while _____(first_name) < _:\n",
    "#             first_name += first_name[_]\n",
    "#         if len(_____) == 1:\n",
    "#             print(f\"Hello {first_name}!\")\n",
    "#         else:\n",
    "#             print(f\"Hello {first_name}, from the house of {list_of_names[_]}\")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
