{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "# 7.&nbsp; Exercises\n",
    "\n",
    "#### Exercise 1\n",
    "\n",
    "Create a list named `lower_names` and fill it with your favourite actors. Include name and surname, all in lowercase (like `john doe`).\n",
    "Then, create a new list `capital_names` with both the names and surnames capitalized (like `John Doe`), by iterating through the first list with a `for` loop.\n",
    "\n",
    "# It's okay to make mistakes!\n",
    "lower_name = [\"zendaya\", \"tom holland\", \"millie bobby brown\", \"anya taylor-joy\", \"noah centineo\"]\n",
    "capital_names = []\n",
    "\n",
    "for actor_name in lower_name:\n",
    "   capital_names.append(actor_name.title())\n",
    "print(capital_names)\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# lower_names = [\"_____ _____\",\"_____ _____\",\"_____ _____\",\"_____ _____\",\"_____ _____\",\"_____ _____\"]\n",
    "# capital_names = []\n",
    "# _____ name in _____:\n",
    "#     capital_names._____(name._____())\n",
    "\n",
    "#### Exercise 2\n",
    "\n",
    "Use the `capital_names` list from the previous exercise and print out only the ones that start with \"A\" or \"J\".\n",
    "\n",
    "# We're all learning here!\n",
    "for name in capital_names:\n",
    "  if name.startswith(\"A\") or name.startswith(\"J\"):\n",
    "    print(f\"{name}\")\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# for name in _____:\n",
    "#     if _____.startswith(\"A\") or name._____(\"J\"):\n",
    "#         print(_____)\n",
    "\n",
    "#### Exercise 3\n",
    "\n",
    "You are given a list of names. Loop through the list and print \"Hello `name`!\" if a name starts with \"A\". If not, print \"Bye `name`!\".\n",
    "\n",
    "names = [\"Justine\",\"Amabel\",\"Karl\",\"Anna\",\"Lina\",\"Sergei\",\"Wang\",\"Aurora\"]\n",
    "\n",
    "# Coding is your superpower; use it to conquer the challenge\n",
    "for name in names:\n",
    "  if name.startswith(\"A\"):\n",
    "    print(f\"Hello {name}\")\n",
    "  else:\n",
    "    print(f\"Bye {name}\")  \n",
    "\n",
    "##### Hint\n",
    "\n",
    "# for _____ in names:\n",
    "#     if name._____(\"A\"):\n",
    "#         print(\"Hello \"+_____+\"!\")\n",
    "#     _____:\n",
    "#         print(\"Bye \"+_____+\"!\")\n",
    "\n",
    "#### Exercise 4\n",
    "\n",
    "Copy the code from last exercise and add a text that gets printed after each iteration of the loop, so it is clearer what\"s going on. (\"Next iteration incoming...\")\n",
    "\n",
    "# Write code with confidence\n",
    "for name in names:\n",
    "  if name.startswith(\"A\"):\n",
    "    print(f\"Hello {name}\")\n",
    "    print(\"Next iteration incoming...\")\n",
    "  else:\n",
    "    print(f\"Bye {name}\")  \n",
    "    print(\"Next iteration incoming...\")\n",
    "\n",
    "##### Hint\n",
    "\n",
    "# for _____ in names:\n",
    "#     if name._____(\"A\"):\n",
    "#         print(\"Hello \"+_____+\"!\")\n",
    "#     _____:\n",
    "#         print(\"Bye \"+_____+\"!\")\n",
    "#     _____(\"Next iteration incoming...\")\n",
    "\n",
    "#### Exercise 5\n",
    "\n",
    "In the previous code, the \"next iteration incoming...\" text gets printed also for the last iteration, which might be confusing for whoever reads the output of this code. Change the code so that this text gets printed in all except the last iteration.\n",
    "\n",
    "##### Hint\n",
    "\n",
    "count = 0\n",
    "for name in names:\n",
    "     if name.startswith(\"A\"):\n",
    "         print(f\"Hello {name}!\")\n",
    "     else:\n",
    "       print(f\"Bye {name}\")    \n",
    "     if count != len(names) -1:\n",
    "         print(\"Next iteration incoming...\")\n",
    "     count += 1\n",
    "\n",
    "# count = _____\n",
    "# for _____ in names:\n",
    "#     if name._____(\"A\"):\n",
    "#         print(\"Hello \"+_____+\"!\")\n",
    "#     if _____ != len(names):\n",
    "#         print(\"Next iteration incoming...\")\n",
    "#     _____ = _____ 1\n",
    "\n",
    "#### Exercise 6\n",
    "\n",
    "You are given a list of numbers. Looping through the list, sum all the numbers and print the result.\n",
    "\n",
    "numbers = [23,45,12,10,25]\n",
    "\n",
    "# Embrace the challenge\n",
    "sum(numbers)\n",
    "\n",
    "total_sum = 0\n",
    "for number in numbers:\n",
    "  total_sum +=number\n",
    "  print(total_sum) \n",
    "\n",
    "##### Hint\n",
    "\n",
    "# total = 0\n",
    "# for number in _____:\n",
    "#     _____ = _____ number\n",
    "# print(_____)\n",
    "\n",
    "#### Exercise 7\n",
    "\n",
    "Create a simple calculator for additions!\n",
    "Repeatedly ask the user to enter numbers. Each time that the user provides input, this input is first converted to float and then added to a variable `total` (which should start from 0).\n",
    "When the user enters \"add\", the loop stops and the running total is printed out.\n",
    "\n",
    "\n",
    "\n",
    "# Bugs are just detours on the road to success; keep coding!\n",
    "\n",
    "total = 0\n",
    "while total >= 0:\n",
    "  random_number = input(\"Please enter a random number \")\n",
    "  if random_number == \"add\":\n",
    "    break\n",
    "    print(total)\n",
    "    total = 1  \n",
    "\n",
    "  random_number = float(random_number)\n",
    "  if random_number >= 0:\n",
    "    total += random_number\n",
    "    print(total)\n",
    "  else:\n",
    "    print(\"Ending loop\")\n",
    "    break \n",
    "\n",
    "##### Hint\n",
    "\n",
    "# total = 0\n",
    "# while True:\n",
    "#     print(\"Enter number or write 'add' to sum all previous inputs.\")\n",
    "#     _____ = input()\n",
    "#     if number == _____:\n",
    "#         break\n",
    "#     else:\n",
    "#         _____ += float(_____)\n",
    "# print(_____)"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
