{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "\n",
    "##### **Exercise 2:**\n",
    "Assign the number corresponding to the present year to the variable `year` and your age to the variable `age`. Operate with both variables to create a new variable called `birth_year`.\n",
    "\n",
    "# Stay persistent; your code will light the way.\n",
    "year = 2025\n",
    "age = 28\n",
    "birth_year = year - age\n",
    "print(birth_year)\n",
    "# but thats not true because my birthday is in March (:\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# _____ = 2022\n",
    "# age = _____\n",
    "# birth_year = _____ - age\n",
    "\n",
    "##### **Exercise 3:**\n",
    "Create a variable called `price` with the value `100`. Then update its value by multiplying it by `2`.\n",
    "\n",
    "# Conquer the challenge one line of code at a time.\n",
    "price = 100\n",
    "price = 100 * 2\n",
    "print(price)\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# price _____ 100\n",
    "# price = _____ * 2\n",
    "\n",
    "## Floats\n",
    "\n",
    "Floats are numbers with decimals.\n",
    "\n",
    "3.\n",
    "\n",
    "They can include the letter e for an exponent:\n",
    "\n",
    "3e2\n",
    "\n",
    "The function `float()` can be used to convert integers into floats.\n",
    "\n",
    "float(24)\n",
    "\n",
    "##### **Exercise 4:**\n",
    "Calculate how many seconds there are in a year. Store that number in a variable called `year_seconds`.\n",
    "\n",
    "# Bugs are just detours on the road to success; keep coding!\n",
    "year_seconds = 365 * 24 * 60 * 60\n",
    "print(year_seconds)\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# year_seconds = 365 * _____ * 60 * _____\n",
    "\n",
    "##### **Exercise 5:**\n",
    "Multiply your result of year_seconds with your age, and store it in a new variable called `life_seconds`.\n",
    "\n",
    "# Celebrate each code snippet as a step toward victory.\n",
    "year_seconds = 365 * 24 * 60 * 60\n",
    "age = 28\n",
    "life_seconds =  year_seconds * age\n",
    "print(life_seconds)\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# life_seconds = year_seconds * _____\n",
    "\n",
    "##### **Exercise 6:**\n",
    "Calculate how many seconds you will spend in this bootcamp. Store it in a variable called `bootcamp`.\n",
    "\n",
    "# Write code with confidence; you're closer to solving the puzzle.\n",
    "bootcamp = (680 * 60 * 60) + (80 * 60 * 60) #bootcamp + primer\n",
    "print(bootcamp)\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# bootcamp = 15 * 5 * _____ * 60 *_____\n",
    "\n",
    "##### **Exercise 7:**\n",
    "Print out the percentage of your life you will spend in this bootcamp.\n",
    "\n",
    "# Coding is the language of problem-solving; you're fluent in it\n",
    "print(bootcamp/life_seconds)\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# print( _____ / life_seconds)\n",
    "\n",
    "## Text Strings\n",
    "\n",
    "You will use text just as much as numbers when programming. Strings are created with either single quotes `'` or double quotes `\"`:\n",
    "\n",
    "print(\"A string with double quotes.\")\n",
    "\n",
    "print('A string with single quotes.')\n",
    "\n",
    "\"That's a string\"\n",
    "'here is a diffrent string'\n",
    "\n",
    "Having two possible quotation signs allows for having strings with quotes inside:\n",
    "\n",
    "print(\"The name of our school is 'WBS CODING SCHOOL', which can be abbreviated to 'WBSCS'.\")\n",
    "\n",
    "print('The name of our school is \"WBS CODING SCHOOL\", which can be abbreviated to \"WBSCS\".')\n",
    "\n",
    "If you need to create a multiple-line string, you can use triple quotes:\n",
    "\n",
    "poem = \"\"\"Hold fast to dreams\n",
    "For if dreams die\n",
    "Life is a broken-winged bird\n",
    "That cannot fly.\n",
    "Hold fast to dreams\n",
    "For when dreams go\n",
    "Life is a barren field\n",
    "Frozen with snow.\"\"\"\n",
    "\n",
    "print(poem)\n",
    "\n",
    "You can create a string out of another data type with `str()`:\n",
    "\n",
    "# https://www.w3schools.com/python/ref_func_str.asp\n",
    "\n",
    "str_88 = str(88)\n",
    "print(str_88)\n",
    "\n",
    "type(str_88)\n",
    "\n",
    "Some characters in python can have a special meaning.\n",
    "By using a backslash `\\` preceding a character, we \"escape\" its usual meaning and give a special meaning to it.\n",
    "\n",
    "For example, `\\n` will add a new line, and `\\t` will add a tab.\n",
    "\n",
    "print(\"This is the first line.\\nAnd this is the second one.\")\n",
    "\n",
    "print(\"Before the tab.\")\n",
    "print(\"\\tAnd after the tab.\")\n",
    "\n",
    "Similarly, you can escape quotes by using `\\`:\n",
    "\n",
    "fact = \"The world's largest rubber duck was 54'2\\\" by 67'7\\\" by 105'.\"\n",
    "print(fact)\n",
    "\n",
    "If you need to use a backslash inside your string, you type `\\\\`: the first backslash escapes the second one.\n",
    "\n",
    "print(\"Please contemplate a single, one —and only one— backslash: \\\\.\")\n",
    "\n",
    "By typing `r` before the quotes, we denote a string as a _raw string_, which will ignore any special meaning:\n",
    "\n",
    "raw_str = r\"This will not create a new line \\n and here, we will see two backslashes \\\\.\"\n",
    "print(raw_str)\n",
    "\n",
    "You can combine strings using `+` and multiply them with `*`:\n",
    "\n",
    "print(\"Data\" +\" \"+ \"Science\")\n",
    "\n",
    "print(\"Data\"*10)\n",
    "\n",
    "Using `[]` you can grab certain characters from a string by specifying their position\n",
    "- We use positive numbers to start counting from the begining of a string. The 1st letter is position `[0]`\n",
    "- We use negative numbers to start counting from the end of a string. The last letter is position `[-1]`\n",
    "\n",
    "letters = \"abcdefghijklmnopqrstuvwxyz\"\n",
    "\n",
    "letters[0]\n",
    "\n",
    "letters[2]\n",
    "\n",
    "letters[-1]\n",
    "\n",
    "letters [-4]\n",
    "\n",
    "You can _slice_ a string using `[start:end]`. Note that the start is inclusive, but the end is not:\n",
    "\n",
    "letters[1:5]\n",
    "\n",
    "If you don't specify the start, the slice will start at the beginning of the string. The same goes for the end.\n",
    "\n",
    "letters[:4]\n",
    "\n",
    "letters[4:]\n",
    "\n",
    "Counting how many characters there are in a string can be done with `len()`.\n",
    "\n",
    "# https://www.w3schools.com/python/ref_func_len.asp\n",
    "\n",
    "len(letters)\n",
    "\n",
    "len(\"piece of string\")\n",
    "\n",
    "The `split` function lets you break a string into smaller strings. The split occurs every time a certain character appears in the string, such as a comma or full stop.\n",
    "\n",
    "jobs = \"Data Scientist, Data Analyst, Data Engineer, Business Analyst, Marketing Analyst, Analytics Consultant\"\n",
    "\n",
    "jobs\n",
    "\n",
    "# https://www.w3schools.com/python/ref_string_split.asp\n",
    "\n",
    "jobs.split(\",\")\n",
    "\n",
    "You can substitute a character using `replace()`:\n",
    "\n",
    "# https://www.w3schools.com/python/ref_string_replace.asp\n",
    "\n",
    "jobs.replace(\"Data\", \"Duck\")\n",
    "\n",
    "You can specify how many times you want to make that replacement.\n",
    "\n",
    "jobs.replace(\"Data\", \"Duck\", 2)\n",
    "\n",
    "A very common process in data cleaning is to remove preceding and trailing spaces from strings. The function `strip()` does exactly that.\n",
    "\n",
    "wow = \"                     wow                     \"\n",
    "print(wow)\n",
    "\n",
    "# https://www.w3schools.com/python/ref_string_strip.asp\n",
    "\n",
    "wow.strip()\n",
    "\n",
    "There are many more string methods in Python. Browse through them here: https://www.w3schools.com/python/python_ref_string.asp\n",
    "\n",
    "About 99.9% of the time, coding does not mean memorizing functions and knowing them by heart. Instead coding is about being quick in finding the function you need, discovering how to use them, reading the documentation, or simply adapting coding examples from the internet to meet your needs.\n",
    "\n",
    "In the exercises below, you will have to use several Python string methods, in combination with what you have learned here. Use the link from _w3schools_ or google around to complete them.\n",
    "\n",
    "##### **Exercise 8:**\n",
    "Create a Python string with the following text, and assign it to the variable `data_science`:\n",
    "\n",
    "```text\n",
    "Data science is an interdisciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge and insights from noisy, structured and unstructured data, and apply knowledge and actionable insights from data across a broad range of application domains.\n",
    "\n",
    "Data science is related to data mining, machine learning and big data. Data science is a \"concept to unify statistics, data analysis, informatics, and their related methods\" in order to \"understand and analyze actual phenomena\" with data. It uses techniques and theories drawn from many fields within the context of mathematics, statistics, computer science, information science, and domain knowledge. However, data science is different from computer science and information science. Turing Award winner Jim Gray imagined data science as a \"fourth paradigm\" of science (empirical, theoretical, computational, and now data-driven) and asserted that \"everything about science is changing because of the impact of information technology\" and the data deluge.\n",
    "````\n",
    "\n",
    "# Each challenge is a chance for your code to shine.\n",
    "data_science = '''Data science is an interdisciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge and insights from noisy, structured and unstructured data, and apply knowledge and actionable insights from data across a broad range of application domains.\n",
    "\n",
    "Data science is related to data mining, machine learning and big data. Data science is a \"concept to unify statistics, data analysis, informatics, and their related methods\" in order to \"understand and analyze actual phenomena\" with data. It uses techniques and theories drawn from many fields within the context of mathematics, statistics, computer science, information science, and domain knowledge. However, data science is different from computer science and information science. Turing Award winner Jim Gray imagined data science as a \"fourth paradigm\" of science (empirical, theoretical, computational, and now data-driven) and asserted that \"everything about science is changing because of the impact of information technology\" and the data deluge.'''\n",
    "print(data_science)\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# data_science = '''_____'''\n",
    "\n",
    "##### **Exercise 9:**\n",
    "How many characters are there in `data_science`?\n",
    "\n",
    "# Show your skills!\n",
    "len(data_science)\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# _____(data_science)\n",
    "\n",
    "##### **Exercise 10:**\n",
    "Convert all of the `data_science` characters to lower case and save it to a variable called `data_science_lower`.\n",
    "\n",
    "# You've got this!\n",
    "data_science_lower = data_science.lower()\n",
    "print(data_science_lower)\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# https://www.w3schools.com/python/ref_string_lower.asp\n",
    "\n",
    "# _____ = data_science._____()\n",
    "\n",
    "##### **Exercise 11:**\n",
    "How many times does the word \"data\" appear in the string you converted to lower case?\n",
    "\n",
    "# Don't be afraid to be wrong!\n",
    "data_science_lower.count(\"data\")\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# https://www.w3schools.com/python/ref_string_count.asp\n",
    "\n",
    "# data_science_lower._____(\"data\")\n",
    "\n",
    "##### **Exercise 12:**\n",
    "Split the string into sentences whenever there is a fullstop (`.`).\n",
    "\n",
    "# Stay curious and keep coding\n",
    "data_science_lower.split(\". \")\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# https://www.w3schools.com/python/ref_string_split.asp\n",
    "# https://www.w3schools.com/python/ref_string_rsplit.asp\n",
    "\n",
    "# data_science._____(\". \")\n",
    "\n",
    "##### **Exercise 13:**\n",
    "Capitalise the first letter of every word in the string and save it to the variable `data_science_capital`.\n",
    "\n",
    "# You're on the right track; keep coding and stay determined.\n",
    "data_science_capital = data_science_lower.title()\n",
    "print(data_science_capital)\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# https://www.w3schools.com/python/ref_string_title.asp\n",
    "\n",
    "# data_science_capital = data._____()\n",
    "\n",
    "##### **Exercise 14:**\n",
    "Find the index of the word \"Turing\" in the string and save it to the variable `index`.\n",
    "\n",
    "# With every line of code, you're making progress.\n",
    "index = data_science_capital.find(\"Turing\")\n",
    "index\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# https://www.w3schools.com/python/ref_string_index.asp\n",
    "\n",
    "# index = data_science._____(\"_____\")\n",
    "\n",
    "##### **Exercise 15:**\n",
    "In the string `data_science`, replace the name \"Jim Gray\" with the variable `jim`. Save the changed string in the variable `new_data_science`\n",
    "\n",
    "jim = \"James Nicholas Gray\"\n",
    "\n",
    "from os import replace\n",
    "# It's okay to make mistakes!\n",
    "new_data_science = data_science.replace(\"Jim Gray\", \"jim\")\n",
    "print(new_data_science)\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# new_data_science = data_science._____(\"Jim Gray\",_____)\n",
    "\n",
    "## Formatting with f-strings\n",
    "\n",
    "Strings can be concatenated with `+`. Sometimes, you need to [interpolate](https://en.wikipedia.org/wiki/String_interpolation) values into strings.\n",
    "\n",
    "Say, you work for a logistics company and have a script that calculates the number of trucks that should be made ready for the next day. You want this number to be included in the sentence of an email: `\"For tomorrow, we will need x trucks.\"` But replacing x with the number of trucks, which will vary each day.\n",
    "\n",
    "This task is known as formatting strings. It can be confusing to learn this by just browsing the internet because there are many ways to format strings in Python: the old one (using `%`), the new one (using `{}`and `format()`) and the newest one (using `f-strings`).\n",
    "\n",
    "We will only show you how to use f-strings, but be ready to stumble on the other ones at any time!\n",
    "\n",
    "n_trucks = 70\n",
    "date = 'next week'\n",
    "\n",
    "email = f\"For {date}, we will need {n_trucks} trucks.\"\n",
    "\n",
    "print(email)\n",
    "\n",
    "The curly brackets support expressions like these:\n",
    "\n",
    "place = \"main garage\"\n",
    "\n",
    "email = f\"For tomorrow, we will need {n_trucks+10} trucks in the {place.title()}.\"\n",
    "\n",
    "print(email)\n",
    "\n",
    "##### **Exercise 16:**\n",
    "Let's write about how the bootcamp fits into your life. Using the variables `age`,`life_seconds` and `bootcamp` defined above, use an *f-string* to write\n",
    "> I am \\_\\_\\_\\_\\_ years old and will spend \\_\\_\\_\\_\\_% of my life taking the WBS Data Science bootcamp.\n",
    "\n",
    "# You're doing great!\n",
    "\n",
    "f\"I am {age} years old and will spend {bootcamp/life_seconds}% of my life taking the WBS Data Science bootcamp.\"\n",
    "\n",
    "###### **Hint**\n",
    "\n",
    "\n",
    "\n",
    "# f'I am {_____} years old and will spend {_____}% of my life taking the WBS Data Science bootcamp:'"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
